### Library

In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.ops.gen_array_ops import shape
import tensorflow.compat.v1 as tf

### Tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [3]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1)

random_e.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

### Tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [6]:
list_a = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97]
conver_a = tf.convert_to_tensor(list_a)

conver_a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 71, 73, 79, 83, 89, 97])>

In [7]:
var_a = tf.Variable(tf.ones([2,3]))

var_a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
var_value_a=[[2,3,5],[7,11,13]]
var_a.assign(var_value_a)

print("Value of the variable var_a after the assignment:",var_a.read_value())

Value of the variable var_a after the assignment: tf.Tensor(
[[ 2.  3.  5.]
 [ 7. 11. 13.]], shape=(2, 3), dtype=float32)


### Tampilkan dimensi dari kedua variable

In [22]:
###Dimension Reshaping

In [23]:
reshape_a = tf.constant([[2,3,5],[7,11,13],[17,19,23]])
print(reshape_a)
tf.reshape(reshape_a, (3,3))

tf.Tensor(
[[ 2  3  5]
 [ 7 11 13]
 [17 19 23]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  5],
       [ 7, 11, 13],
       [17, 19, 23]])>

In [24]:
###Dimension Squeezing

In [31]:

squeeze_sample_a = tf.random.normal([2,11,17,19,23])
print("size of the original data:",squeeze_sample_a.shape)
squeezed_sample_a = tf.squeeze([2,3,5,7,11])
print("data size after dimension squeezing:",squeezed_sample_a.shape)

size of the original data: (2, 11, 17, 19, 23)
data size after dimension squeezing: (5,)


In [42]:
var_a.assign_add(var_value_a)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4.,  6., 10.],
       [10., 14., 22.]], dtype=float32)>

In [43]:
var_value_a=[[2,3,5],[5,7,11]]

var_a.assign(var_value_a)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  3.,  5.],
       [ 5.,  7., 11.]], dtype=float32)>

### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut(Gunakan Minimal 5 operator)

In [44]:
## PENJUMLAHAN 

In [45]:
x = tf.constant([[2,3], [5,7]])
y = tf.constant([[13,17], [19,23]])

print(tf.add(x,y))

tf.Tensor(
[[15 20]
 [24 30]], shape=(2, 2), dtype=int32)


In [46]:
## PANGKAT

In [47]:
x = tf.constant([[2,3,5], [7,11,13]])
y = tf.constant([[17,19,23], [29,31,37]])

tf.pow(x,y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[     131072,  1162261467, -1883073043],
       [  881932135,  1823198243, -1053241123]])>

In [48]:
## PERKALIAN

In [49]:
x = tf.constant([[2,3], [5,7]])
y = tf.constant([[11,13], [17,19]])

tf.multiply(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 22,  39],
       [ 85, 133]])>

In [50]:
## PEMBAGIAN

In [51]:
x = tf.constant([[2,3], [5,7]])
y = tf.constant([[11,13], [17,19]])

tf.divide(x,y)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.18181818, 0.23076923],
       [0.29411765, 0.36842105]])>

In [55]:
## PENGURANGAN

In [56]:
x = tf.constant([[2,3], [5,7]])
y = tf.constant([[11,13], [17,19]])

tf.subtraction(x,y)

AttributeError: module 'tensorflow.compat.v1' has no attribute 'subtraction'

### Tampilan nilai maksimal dan minimal dari variable random_tensor

In [57]:
### MAKSIMAL

In [58]:
argmax_sample_1 = tf.constant([[2,5,2],[7,5,11],[13,17,19]])
print("input tensor:",argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by column:",max_sample_1.numpy())
print("locate the maximum value by row:",max_sample_2.numpy())

input tensor: [[ 2  5  2]
 [ 7  5 11]
 [13 17 19]]
locate the maximum value by column: [2 2 2]
locate the maximum value by row: [1 2 2]


In [59]:
### MINIMAL

In [60]:
argmin_sample_1 = tf.constant([[2,5,2],[7,5,11],[13,17,19]])
print("input tensor:",argmin_sample_1.numpy())
min_sample_1 = tf.argmin(argmin_sample_1, axis=0)
min_sample_2 = tf.argmin(argmin_sample_1, axis=1)
print("locate the minimal value by column:",min_sample_1.numpy())
print("locate the minimal value by row:",min_sample_2.numpy())

input tensor: [[ 2  5  2]
 [ 7  5 11]
 [13 17 19]]
locate the minimal value by column: [0 0 0]
locate the minimal value by row: [0 1 0]


### Tampilan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [63]:
concat_sample_1 = tf.random.normal([2,5,7,11,13])
concat_sample_2 = tf.random.normal([2,5,7,11,13])
print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

sizes of the original data: (2, 5, 7, 11, 13) (2, 5, 7, 11, 13)
size of the concatenated data: (4, 5, 7, 11, 13)


In [64]:
stack_sample_1 = tf.random.normal([2,5,7,11,13])
stack_sample_2 = tf.random.normal([2,5,7,11,13])

print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)

stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

sizes of the original data:  (2, 5, 7, 11, 13) (2, 5, 7, 11, 13)
size of the concatenated data: (2, 2, 5, 7, 11, 13)


### Tampilan hasil sorting dari Descending

In [86]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="DESCENDING")
print("tensor sorted in descending order:",sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1,direction="DESCENDING")
print("indexes of elements in descending order:",sorted_sample_2.numpy())

input tensor: [6 1 2 5 7 4 9 0 8 3]
tensor sorted in descending order: [9 8 7 6 5 4 3 2 1 0]
indexes of elements in descending order: [6 8 4 0 3 5 9 2 1 7]
